version: '3.8'
services:
  mysql:
    ports:
      - "3306:3306" # Exposing MySQL port to host

  redis:
    ports:
      - "6379:6379" # Exposing Redis port to host

  clickhouse:
    ports:
      - "8123:8123" # Exposing ClickHouse HTTP port to host
      - "9000:9000" # Exposing ClickHouse Native Protocol port to host

  backend:
    environment:
      AUTH_ENABLED: true
      AUTH_UI_URL: https://booster-id.us.auth0.com/userinfo
      AUTH_SDK_URL: https://booster-id.us.auth0.com/userinfo
      AUTH_IS_AUTH0: true
    ports:
      - "8080:8080" # Exposing backend HTTP port to host
      - "3003:3003" # Exposing backend OpenAPI specification port to host

  python-backend:
    ports:
      - "8000:8000" # Exposing Python backend HTTP port to host

  frontend:
    ports:
      - "5173:5173" # Exposing frontend server port to host

  aifindr-evaluations-runner:
    env_file:
      - ../../apps/aifindr-evaluations-runner/.env
